### ISSUE TITLE
Re-rewrite babel-sublime

### ISSUE THREAD

**Issue by zertosh** [babel/babel-sublime#293]
This issue tracks all of the TODOS, issues and progress of rewriting the grammar.

---

The `tmLanguage` format has a lot of limitations (e.g. a single regex can't match across lines, no backtracking, etc) - a "perfect" grammar for flow-typed JS is impossible. "Perfect" means (1) every token has a correct hierarchy of scopes (or none as appropriate) and (2) non-standard formatting doesn't interfere (e.g. comments in weird places `class /*cmt*/ Bar {}`) – all the while not doing too many expensive regex look-arounds.

Some things can't be supported at all, like scoping arrow functions params when the opening `(` is not on the same line as the `=>`. Others can be supported if you forgo certain scope hierarchy correctness. I'm willing to make this trade-off since the benefit is usually better theme syntax highlighting at the expense of correct (aka expected) "expand selection to scope". Another trade-off is the extent to which something is included in Symbols (for "Goto definition" and "Goto Symbols"). These are some examples of what should be included: (1) any `class` or `class` method, (2) named functions, (3) short-methods on objects. Others like object keys that have functions will not be included. I'll do my best to document these behaviors.

## Goals

* The grammar should be in `tmLanguage` format (not [`sublime-syntax`](https://www.sublimetext.com/docs/3/syntax.html)) so it can be reused in Atom and VSCode.
  * In future, add support for `sublime-syntax` to Atom (https://github.com/atom/first-mate/issues/50).
* This package should *only* be the grammar - so no transpiling support, snippets or additional themes.
* Support flow, jsx, and anything else that's parsable by babel.

## TODO

* [x] Remove cruft from repo. (https://github.com/babel/babel-sublime/compare/114724bd15897c7f18a3aba64e7e300b3267f365...8168983710be6d2bbbfbb186b57a0936deb3fd52)
* [x] Create tests for the **current** grammar. (14d9f439a04d0305e0b61b791c82fe600b1e061a)
* [ ] Sync scope names with https://github.com/sublimehq/Packages/blob/master/JavaScript/JavaScript.sublime-syntax.
  * Document notable exceptions.
* [ ] Screenshots, README for users and contributors.
* [ ] Wiki explaining the difference between the grammar and the theme. (Will save time with issues).
* [ ] Fix indentation #261.
* [ ] New grammar.

**Comment by caesarsol** [comment]
I like where this is going!
Just a couple notes:
- I thought that tmLanguage and sublime-syntax files were translatable, isn't this true?
- My opinion is that the syntax highlighting should enhance the syntax but not check it, that's work for a linter! So I agree on your point.

I'm available for any help, especially on the testing since I have yet to understand the syntax definition syntax!

**Comment by zertosh** [comment]
> I thought that tmLanguage and sublime-syntax files were translatable, isn't this true?

You can go from `tmLanguage` to `sublime-syntax` easily, but there are features in `sublime-syntax` that you can't emulate in `tmLanguage`.

**Comment by faergeek** [comment]
@zertosh not exactly like that. AFAIK .tmLanguage supports backrefs, but .sublime-syntax does not.

**Comment by max-mykhailenko** [comment]
@zertosh Waiting for any progress in this. Do you plan to continue developing or I should switch to atom for regular updates?

**Comment by nktssh** [comment]
Maybe, #301 also should be added to list?

**Comment by AriaMinaei** [comment]
I imported VSCode's tmLanguage files and they work perfectly now.

Download the syntax from [here](https://github.com/Microsoft/vscode/tree/master/extensions/javascript/syntaxes) and convert them from JSON to PList using [PackageDev](https://github.com/SublimeText/PackageDev#editing-existing-syntax-definitions).

**Comment by faiwer** [comment]
@AriaMinaei, how did you connect it to ST3? I converted that JSON into Plist, also downloaded tmLanguage file. I put them into `~/.config/sublime-text-3/Packages/jscode`. I saw in st3-console `generating syntax summary` without errors. But in menu I saw only 1 new item: `Set syntax: Regular Expressions Javascript`.

**Comment by caesarsol** [comment]
@faiwer It's working for me, did you rename the `.tmLanguage.plist` to `.tmLanguage`?

**Comment by faiwer** [comment]
@caesarsol, thank you! All right, now. 
I did it wrong way before. I've copied `.tmLanguage` from `vscode` repository, converted json-file to `plist`, and put both files in one directory in `packages`.

**Comment by zertosh** [comment]
@caesarsol @faiwer, the issues you're going to run into by using an unmodified TS grammar are (1) Jump to definition and symbols are going to be very incomplete because Sublime depends entirely on the grammar scopes to determine this - VSCode doesn't, so their grammar isn't built for that, (2) some JS-only constructs like labels do not always work correctly

**Comment by AriaMinaei** [comment]
@zertosh Actually I'm using the JS grammar from VSCode. I'd have to say that it's not absolutely 'perfect', but it works in more cases than babel-sublime last time that I checked. I'd still love to switch back to babel-sublime once the issues are fixed, of course.

**Comment by faiwer** [comment]
Unfortunately VSCode grammar-syntax has a lot of problems too :( I'm starting to think about using WebStorm.
@zertosh Do you plan to continue developing the plugin?

**Comment by aristidesfl** [comment]
Have you considered forking [javascript-ultimate](https://github.com/JoshuaWise/javascript-ultimate) and adding [JSX](https://github.com/JoshuaWise/javascript-ultimate/issues/4)?

`javascript-ultimate` follows the ES6 spec exactly, has pretty advanced regular expression comprehension, and [claims](https://github.com/JoshuaWise/javascript-ultimate/issues/20) to be the only javascript syntax which highlights invalid code as you type. 

Are there any other features that `babel-sublime` providers over `javascript-ultimate` besides JSX support?

**Comment by max-mykhailenko** [comment]
Also we can add jsx support to native sublime javascript syntax and forget about babel syntax https://github.com/sublimehq/Packages/issues/860

**Comment by andreidcm** [comment]
@AriaMinaei, got vscode syntax and converted it with PackageDev and works (wanted it for Flow syntax), but the SublimeLinter errors stop showing, I see the errors in the console but they're not highlighted.
Any pointers?

**Comment by AriaMinaei** [comment]
@andreidcm The "syntax_map" config for SublimeLinter should fix that.

**Comment by andreidcm** [comment]
@AriaMinaei, Thx, the lint errors that I see in the console are from ESLint Formatter not SublimeLinter.
Already set `syntax_map` in SublimeLinter settings:
```javascript
"syntax_map": {
    ...
    "JavaScript (VSCode)": "javascript",
    ...
}
```
Double checked the name inside `JavaScript (VSCode).tmLanguage` but still no go.

**Comment by andreidcm** [comment]
@AriaMinaei, Pff, just read the [SublimeLinter Docs](https://sublimelinter.readthedocs.io/en/latest/global_settings.html#syntax-map). 

> The syntax names in the map should be lowercase

Changed to `"javascript (vscode)": "javascript"` and all's well.

Thx :)

**Comment by rattrayalex-stripe** [comment]
@zertosh What's the status? Do you need help with this?

**Comment by Diokuz** [comment]
Any chance to have simple flow support in near future?

![2017-11-03 10 46 10](https://user-images.githubusercontent.com/2929442/32364141-398c369e-c084-11e7-914d-abd9e78ea092.png)

**Comment by max-mykhailenko** [comment]
Add a semicolon after type definition

```
type Abc  = {|
  name: string,
|};
```

**Comment by reimertz** [comment]
@max-mykhailenko That works but it breaks if you run flow together with prettier and run `semi: false`.

**Comment by kylebebak** [comment]
@zertosh 

It might be time to tell folks this project is no longer actively developed. If there were any progress being made it seems like this issue would be the one to follow, and no one has even commented in the past 9 months.

**Comment by max-mykhailenko** [comment]
I'm happy user of https://github.com/borela/naomi now

**Comment by kylebebak** [comment]
Interesting, I'll check it out. I'm currently trying <https://github.com/Thom1729/Sublime-JS-Custom>.

**Comment by Thom1729** [comment]
I'm closing this issue in favor of #379.
